/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.Empleados;

/**
 *
 * @author david
 */
public class FormLogin extends javax.swing.JFrame {

    private Empleados objEm;

    private ArrayList<Empleados> listaEmp = new ArrayList();

    /**
     * Creates new form FormAdministracion
     */
    public FormLogin() {
        objEm = new Empleados();
        initComponents();
        Persistencia();

    }

    public ArrayList<Empleados> getListaEmp() {
        return listaEmp;
    }

    public void setListaEmp(ArrayList<Empleados> listaEmp) {
        this.listaEmp = listaEmp;
    }

    

    public JTextField getTxtCargo() {
        return txtCargo;
    }

    public void setTxtCargo(JTextField txtCargo) {
        this.txtCargo = txtCargo;
    }

    public JPasswordField getTxtContraseñaAd() {
        return txtContraseñaAd;
    }

    public void setTxtContraseñaAd(JPasswordField txtContraseñaAd) {
        this.txtContraseñaAd = txtContraseñaAd;
    }

    public JTextField getTxtNombreAD() {
        return txtNombreAD;
    }

    public void setTxtNombreAD(JTextField txtNombreAD) {
        this.txtNombreAD = txtNombreAD;
    }

    public ArrayList Persistencia() {
        ArrayList lista = new ArrayList();
        DataInputStream archivo;
        String cadena;

        try {
            archivo = new DataInputStream(new FileInputStream("Empleados.txt"));
            while ((cadena = archivo.readLine()) != null) {
                String campo[] = cadena.split(";");
                objEm = new Empleados();
                //objEm.setId(campo[0]);
                objEm.setNombre(campo[0]);
                objEm.setCargo(campo[1]);
                objEm.setContraseña(campo[2]);
                this.listaEmp.add(objEm);

            }

        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error de E/S" + e.getMessage(), "Leer Archivo", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            Logger.getLogger(FormClientes.class.getName()).log(Level.SEVERE, null, e);
        }
        return lista;
    }

    public JButton getBtnIngresarAD() {
        return btnIngresarAD;
    }

    public void setBtnIngresarAD(JButton btnIngresarAD) {
        this.btnIngresarAD = btnIngresarAD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreAD = new javax.swing.JTextField();
        txtContraseñaAd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        btnIngresarAD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Cargo:");

        jLabel3.setText("Contraseña");

        jLabel5.setBackground(new java.awt.Color(51, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ADMINISTRACION SUPERMERCADO");
        jLabel5.setOpaque(true);

        btnIngresarAD.setText("Ingresar Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCargo)
                    .addComponent(txtContraseñaAd, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(txtNombreAD))
                .addGap(37, 37, 37)
                .addComponent(btnIngresarAD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresarAD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContraseñaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public boolean validar(String nombre, String cargo, String contraseña) throws FileNotFoundException, IOException {
        File archivo = new File("Empleados.txt");
        RandomAccessFile fichero = new RandomAccessFile(archivo, "rw");
        String cadena;
        if (fichero != null) {
            fichero.seek(0);
            while (fichero.getFilePointer() < fichero.length()) {
                cadena = fichero.readLine();

                String campo[] = cadena.split(";");
                if (nombre.equals(campo[0]) && cargo.equals(campo[1]) && contraseña.equals(campo[2])) {

                    fichero.close();
                    return true;
                }
            }
            return false;
        }
        return false;

    }

    public void mostrar() {
        for (int i = 0; i < listaEmp.size(); i++) {
            System.out.println(listaEmp.get(i).getNombre() + " " + listaEmp.get(i).getCargo() + " " + listaEmp.get(i).getContraseña());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JPasswordField txtContraseñaAd;
    private javax.swing.JTextField txtNombreAD;
    // End of variables declaration//GEN-END:variables
}
