/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author david
 */
public class Supermercado extends javax.swing.JFrame implements Runnable {

    private int x = 20;
    private Thread hilo;

    /**
     * Creates new form Supermercado
     */
    public Supermercado() {
        initComponents();
        hilo = new Thread(this);
        hilo.start();
    }

    public JMenuItem getjMenuEmpleados() {
        return jMenuEmpleados;
    }

    public void setjMenuEmpleados(JMenuItem jMenuEmpleados) {
        this.jMenuEmpleados = jMenuEmpleados;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenuItem getjMenuSalir() {
        return jMenuSalir;
    }

    public void setjMenuSalir(JMenuItem jMenuSalir) {
        this.jMenuSalir = jMenuSalir;
    }

    public JMenuItem getjMenuCli() {
        return jMenuCli;
    }

    public void setjMenuCli(JMenuItem jMenuCli) {
        this.jMenuCli = jMenuCli;
    }

    public JMenuItem getjMenuSuper() {
        return jMenuSuper;
    }

    public void setjMenuSuper(JMenuItem jMenuSuper) {
        this.jMenuSuper = jMenuSuper;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMov = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEmpleados = new javax.swing.JMenuItem();
        jMenuCli = new javax.swing.JMenuItem();
        jMenuSuper = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMov.setText("David Santiago Aldana Pita");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/supemercado.jpg"))); // NOI18N

        jMenu1.setText("Menús");

        jMenuEmpleados.setText("Empleados");
        jMenuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEmpleados);

        jMenuCli.setText("Clientes");
        jMenu1.add(jMenuCli);

        jMenuSuper.setText("Supermercado");
        jMenuSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuper);

        jMenuSalir.setText("Salir");
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMov)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEmpleadosActionPerformed

    private void jMenuSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSuperActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void run() {
        int incremento = 30;
        while (true) {
            this.lblMov.setBounds(x, -5, 160, 25);

            if (x < 20) {
                this.lblMov.setForeground(Color.MAGENTA);
                incremento = 10;
            }
            if (x > 220) {
                this.lblMov.setForeground(Color.red);
                incremento = -10;
            }
            try {
                hilo.sleep(200);
            } catch (InterruptedException ex) {
                Logger.getLogger(Supermercado.class.getName()).log(Level.SEVERE, null, ex);
            }
            x = x + incremento;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCli;
    private javax.swing.JMenuItem jMenuEmpleados;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuSuper;
    private javax.swing.JLabel lblMov;
    // End of variables declaration//GEN-END:variables
}
